name: Prepare
description: Prepares the repo for a typical CI job

inputs:
  node-version:
    required: false
    description: "`node-version` passed to `actions/setup-node`."
    default: "20"

runs:
  using: "composite"
  steps:
    - name: Configure Git
      run: |
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name ${GITHUB_ACTOR}
      shell: bash
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Rush Install
      shell: bash
      run: node common/scripts/install-run-rush.js install

    - name: Rush rebuild
      shell: bash
      run: node common/scripts/install-run-rush.js rebuild --verbose
