name: Lint Spelling

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  workflow_call:

env:
  RUSH_ALLOW_WARNINGS_IN_SUCCESSFUL_BUILD: 1

jobs:
  lint_spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - run: node common/scripts/install-run-rush.js lint:spelling --verbose
