name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: Release
  cancel-in-progress: false

env:
  RUSH_ALLOW_WARNINGS_IN_SUCCESSFUL_BUILD: 1

jobs:
  lint_js:
    uses: ./.github/workflows/lint-js.yml
  lint_knip_dev:
    uses: ./.github/workflows/lint-knip-dev.yml
  lint_knip_prod:
    uses: ./.github/workflows/lint-knip-prod.yml
  lint_markdown:
    uses: ./.github/workflows/lint-markdown.yml
  lint_spelling:
    uses: ./.github/workflows/lint-spelling.yml
  lint_yaml:
    uses: ./.github/workflows/lint-yaml.yml
  test_js:
    uses: ./.github/workflows/test-js.yml
  typecheck:
    uses: ./.github/workflows/typecheck.yml

  release:
    needs:
      - lint_js
      - lint_knip_prod
      - lint_markdown
      - lint_spelling
      - lint_yaml
      - test_js
      - typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: ./.github/actions/prepare

      - name: Build
        run: node common/scripts/install-run-rush.js build --verbose

      - name: Bump version
        run: node common/scripts/install-run-rush.js version --bump --ensure-version-policy --ignore-git-hooks --verbose

      - name: Publish
        run: node common/scripts/install-run-rush.js publish --apply --publish --include-all --ignore-git-hooks --npm-auth-token ${{ secrets.NPM_TOKEN }} --verbose

